Sprint 2
AnnaPershina/Beauty-World pull request #3
Opened 2021-03-22 04:11 UTC by AnnaPershina

2021-03-24 08:53 UTC, studenttsu requested changes
Привет) Хорошая, большая работа! Есть моменты, которые хотелось бы поправить

1) Правки по комментариям
2) Разобраться в шапке с наложение фона девушки на текст при сжатии размера экрана (z-index). На мобилке можно фон с девушкой скрыть
3) Привести к стилю макета форму в Контактах

2021-03-24 08:53 UTC, studenttsu commented on src/scss/components/_button.scss
> +  border-color: #FB9475;
`можно лучше`

![image](https://user-images.githubusercontent.com/12005449/112280778-f313d880-8cb7-11eb-9c87-ac58b814bafe.png)

Стоит добавить `border: 0; outline: 0; cursor: pointer;`, чтобы не было чёрной обводки как сейчас и при наведении появился нужный курсор.

Нужно добавить стиль при наведении на кнопку (затемнение фона, увеличение) и плавность перехода (transition)

2021-03-24 08:53 UTC, studenttsu commented on src/index.html
> +                        <div class="service__picture">
`нужно поправить`

А где .service потерялся? По БЭМ элементы не могут быть оторваны от своего блока
Проверить в других местах

2021-03-24 08:53 UTC, studenttsu commented on src/scss/main.scss
> +}
`можно лучше`

Стоит давать коду "воздуха" - добавить пустые строки между смысловыми блоками кода - так код легче читать

2021-03-24 08:53 UTC, studenttsu commented on src/scss/main.scss
> +    list-style-type: none;
`можно лучше`

За форматированием кода всё-таки лучше следить

2021-03-24 08:53 UTC, studenttsu commented on src/scss/main.scss
> +      //  max-width: 568px;
`нужно поправить`

Не стоит оставлять код "на потом"

2021-03-29 10:51 UTC, AnnaPershina commented
Привет! Исправила замечания.

2021-03-29 10:55 UTC, studenttsu approved these changes

2021-03-29 10:56 UTC, merged